version: "3.5"

services:

  image:
    container_name: dockerphp
    build:
      context: .
    ports:
        - 8001:80
    volumes:
      - .:/var/www/html/

  db:
      image: postgres:9.5.11
      ports:
        - 5432:5432
      restart: always
      environment:
        POSTGRES_PASSWORD: example

networks:
  default:
    name: dockerGaia
    external: true


  

